env:
  browser: true
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - 'react-hooks'
  - '@typescript-eslint'
rules:
  quotes: 
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  eol-last:
    - error
    - always
  'react/prop-types':
    'off'
  'react/display-name':
    'off'
