name: deploy
on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'gatsby*'
      - ".github/workflows/deploy.yml"
jobs:
  build-and-deploy:
    env:
      DEPLOY_DIRECTORY: "public"
      REPO_PATH: ${{ github.workspace }}
      REPO_NAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH client and start ssh-agent.
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      - name: Clone and checkout.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Installing Yarn.
        run: curl -o- -L https://yarnpkg.com/install.sh | bash
        shell: bash

      - name: Install dependencies and build website.
        run: yarn install && yarn build -- --prefix-paths

      - name: Setup Python v3.8.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install AWS-CLI.
        run: python -m pip install awscli

      - name: Deploy static assets to S3 bucket.
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_ASSETS_BUCKET: ${{ secrets.S3_ASSETS_BUCKET }}
        run: |
          aws s3 sync $REPO_PATH/$DEPLOY_DIRECTORY s3://$S3_ASSETS_BUCKET/p/$REPO_NAME \
          --exclude "*.html" --exclude "*.webmanifest" \
          --exclude ".git*" --exclude "README.md" \
          --delete --acl public-read

      - name: Deploy site to EC2.
        env:
          WEB_PATH: ${{ secrets.EC2_WEB_PATH }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          rsync -avP --delete-excluded \
          --include="*.html" --include="*.webmanifest" \
          --exclude=".git*" --include="*/" --exclude="*" \
          --rsync-path="mkdir -p $WEB_PATH/$REPO_NAME && rsync" \
          -e "ssh -o StrictHostKeyChecking=no" \
          $REPO_PATH/$DEPLOY_DIRECTORY/. $USERNAME@$HOST:$WEB_PATH/$REPO_NAME
          echo "getting rid of empty directories generated by rsync."
          ssh $USERNAME@$HOST "find $WEB_PATH/$REPO_NAME -type d -empty -delete"

